### ISSUE TITLE
Misssing COPY INTO from STDIN functionality

### ISSUE THREAD

**Issue by gbrian** [MonetDB/monetdb-nodejs#1]
Hi,

I'm planning using REST API for bulk loading. Following documentation COPY INTO seems to be the way to manage. I can't see any implementation on the REST API so I'm thinking about adding myself-  fingers crossed :) -. 

The idea is to stream the coming data into mapi connection avoiding intermediate buffer/files.

Following this example seems quite straight forward http://dev.monetdb.org/hg/MonetDB/file/tip/java/example/SQLcopyinto.java.

**Comments:**
* Will this implementation make use of multiple threads?

* From java example: Do I have to send this "s" character before?
```
   query = "COPY INTO example FROM STDIN USING DELIMITERS ',','\\n';";
			// the leading 's' is essential, since it is a protocol
			// marker that should not be omitted, likewise the
			// trailing semicolon
			out.write('s');
			out.write(query);
			out.newLine();
   ...
```

Thanks in advance

**Comment by gbrian** [comment]
Next COPY INTO test is not working, any idea why?
```javascript

var utils = require('../src/utils.js');
var MapiConnection = require('../src/mapi-connection.js');
var optionDefinition = {
    host: {
        type: 'string',
        dflt: 'localhost'
    },
    port: {
        type: 'number',
        dflt: 50000,
        transform: parseInt
    },
    dbname: {
        type: 'string'
    },
    user: {
        type: 'string',
        dflt: 'monetdb'
    },
    password: {
        type: 'string',
        dflt: 'monetdb'
    },
    language: {
        type: 'string',
        dflt: 'sql'
    },
    defaultSchema: {
        type: 'string',
        dflt: 'sys'
    },
    timezoneOffset: {
        type: 'number',
        dflt: new Date().getTimezoneOffset(), // offset in minutes
        transform: parseInt
    },
    maxReconnects: {
        type: 'number',
        dflt: 10,
        transform: parseInt,
        changeable: true
    },
    reconnectTimeout: {
        type: 'number',
        dflt: 2000,
        transform: parseInt,
        changeable: true
    },
    prettyResult: {
        type: 'boolean',
        dflt: false,
        transform: parseBool,
        changeable: true
    },
    logger: {
        type: 'function',
        dflt: console.log,
        changeable: true
    },
    warnings: {
        type: 'boolean',
        dflt: true,
        transform: parseBool,
        changeable: true
    },
    warningFn: {
        type: 'function',
        dflt: utils.warning,
        changeable: true
    },
    debug: {
        type: 'boolean',
        dflt: false,
        transform: parseBool,
        changeable: true
    },
    debugFn: {
        type: 'function',
        dflt: utils.debug,
        changeable: true
    },
    debugRequests: {
        type: 'boolean',
        dflt: false,
        transform: parseBool,
        changeable: true
    },
    debugRequestFn: {
        type: 'function',
        dflt: utils.debugRequest,
        changeable: true
    },
    debugMapi: {
        type: 'boolean',
        dflt: false,
        transform: parseBool,
        changeable: true
    },
    debugMapiFn: {
        type: 'function',
        dflt: utils.debugMapi,
        changeable: true
    },
    testing: {
        type: 'boolean',
        dflt: false,
        transform: parseBool
    }
};

function parseOptions(opts, globalOpts) {
    if(!opts) opts = {};
    // Construct new options object by reducing the options found in the definitions object
    var result = Object.keys(optionDefinition).reduce(function(o, option) {
        var definition = optionDefinition[option];
        var given = opts[option];
        var parsed = globalOpts ? globalOpts[option] : undefined;
        if(given === undefined) {
            if (parsed === undefined && definition.dflt === undefined) {
                // only fail if we are not constructing the global opts, since global opts
                // might miss required options, which then have to be filled in by local options
                if(!globalOpts) return o;
                throw new Error('Required option "' + option + '" not found..');
            }
            o[option] = parsed !== undefined ? parsed : definition.dflt;
            return o;
        }
        if(typeof(given) != definition.type) {
            throw new Error(
                'Option "' + option + '" has the wrong type. ' +
                'Expected: "' + definition.type + '"' +
                'Given: "' + typeof(given) + '"'
            );
        }
        o[option] = definition.transform ? definition.transform(given) : given;
        return o;
    }, {});

    // report any unrecognized options if debug mode is set on the new options object
    if(result.warnings) {
        Object.keys(opts).forEach(function(option) {
            if(result[option] === undefined) {
                result.warningFn(result.logger, 'Unrecognized option "' + option + '"');
            }
        });
    }

    return result;
}
function parseBool(b) { return !!b }


var self = {};
self.mapiConnection = new MapiConnection(parseOptions({
    host     : 'localhost', 
    port     : 50000, 
    dbname   : 'demo', 
    user     : 'monetdb', 
    password : 'monetdb',
    logger: console.log, 
    warnings: false, 
    debug: true,
    debugRequests: true,
    debugMapi: true
}));

function open(){
	self.mapiConnection.connect().then(function(){
		console.log(arguments);
	},function(){
		console.log(arguments);
	});
}

function close(){
	self.mapiConnection.close();
	self.mapiConnection.destroy();
}

function query(query){
	open();
	self.mapiConnection.request(query)
		.then(function(res){
			console.log("ok");
			console.log(res);
			close();
		},function(err){
			console.log("error");
			console.log(err);
			close();
		});
}
//var 
query("sCOPY INTO foo FROM STDIN USING DELIMITERS ',','\\n';"
	+ "\n"
	+ "100,10,0,'10'\n"
	+ "\n");

query("sSELECT * FROM foo;");
```

**Comment by rcijvat** [comment]
Hi gbrian,

Thanks for trying out the NodeJS modules for MonetDB, and I am terribly sorry for the late reply. I was not notified automatically of issues that appeared here, but since I turned on all notifications now, feel free to ask questions and they will be answered quickly.

For the problem you describe above, consider using the NodeJS import module that we also developed. It automatically detects the configurations of your file, then creates a table and finally constructs and executes a COPY INTO statement:

https://www.npmjs.com/package/monetdb-import

Let me know if you have any more problems.

**Comment by gbrian** [comment]
Hi @rcijvat ,

Thanks. My plan is to connect an aggregate system output live with MonetDB so (initially) won't be a file, specially if this is an in-memory process.

Do you think is this possible ?

**Comment by rcijvat** [comment]
I am not sure about that, that goes beyond the scope of the NodeJS client for MonetDB. It depends on whether the COPY INTO statement can deal with streams instead of files. This might be something to ask on the monetdb user-list (you have to subscribe first). See this page for more on the mailing lists:
https://www.monetdb.org/Developers/Mailinglists

If you post your question there, the whole core MonetDB developer team and all users (who also might have hints) receive your question.

**Comment by gbrian** [comment]
Ok, thanks! I'll do.
BTW Nice job, closing issue! ;)

**Comment by gbrian** [comment]
**From monetdb user list:**

If you try using the NodeJS module for this, try sending these queries to a MapiConnection object (low level), not a MonetDBConnection object (high level). The MonetDBConnection object that you are trying to use packs everything in between an 's' and a ';', including the data you want stored in your table. So you would get something like this (not
tested):

MapiConnection = require("monetdb/src/mapi-connection.js");

var conn = new MapiConnection(..your db options here..); conn.connect();

conn.request("sCOPY INTO foo FROM STDIN USING DELIMITERS ',', '\\n';"); conn.request("100,10,0,'10'\\n");

If you cannot get this to work, please show your attempt.

**Comment by rcijvat** [comment]
Yes, I wrote that, after I saw that there actually was a construct that allows for copying into a table using the stdin keyword. Sorry about not seeing that before. Give the answer a try, and let me know if it works. If not, please give me your attempt, and I will try to find where it fails.
