### ISSUE TITLE
All parallel requests will fail if failed at least one

### ISSUE THREAD

**Issue by mayanika** [MonetDB/monetdb-nodejs#12]
Hello

I'm using this library for only a week but i faced with an issue: if I send 3 request and some of this requests has invalid SQL then all 3 will be failed with an error. I noticed that the problem is with "prepare" inside of .query(). If queries are complete (no array of values to prepare) then failed will be only invalid.
(sorry for my english);

Here are the code: https://pastebin.com/DxDSDAJv (notice that second and third requests are invalid by SQL in SELECT fields list)

Result if run all: ` ![image](https://user-images.githubusercontent.com/16245186/77052455-83e51380-69d5-11ea-9188-d0b8bcce5200.png)

Result if I comment two invalid queries (second and third):
![image](https://user-images.githubusercontent.com/16245186/77052519-99f2d400-69d5-11ea-9635-a734402feb07.png)

**Comment by sstalin** [comment]
Hi mayanika,
Apologies for the super late response.  The issue you observed is related to a another open  issue in monetdb itself see https://www.monetdb.org/bugzilla/show_bug.cgi?id=6832. So, the problem is not in the monetdb-nodejs library.
