### ISSUE TITLE
Not possible to get affected rows for UPDATE

### ISSUE THREAD

**Issue by mayanika** [MonetDB/monetdb-nodejs#13]
Hello

I am trying to get number of affected rows on UPDATE and can't find how to do that. 
**.query()**  - returns only empty object for UPDATE. 
**.querystream()** - hits **.on('end')** with a single **null** in **arguments**

Is there any way to get it somehow? I need to implement upserts functionality in my application.

**Comment by mayanika** [comment]
I found that in mapi-connection.js -> _parseResponse actually receives that data as: 
`&2 0 -1 210829 1994 0 0
where zero after &2 is an amount of rows but _parseResponse just ignores parsing of such response types :(

**Comment by sstalin** [comment]
accepting your fix for above issue
