### ISSUE TITLE
String of "NULL" is being returned as literal `null` in query results

### ISSUE THREAD

**Issue by MattCollins84** [MonetDB/monetdb-nodejs#15]
If I do a query like this from `mclient` (please forgive the crazy column names):

````
sql>SELECT "_hdl", "up53DzBISPq248wq7IRBGg", "5gOMz5JNTKud05cCiAsiRA" FROM "eic39_tagged_item" WHERE "_hdl" = 'KQdIrIUNQIyMAxJWpazNAw';
+------------------------+------------------------+------------------------+
| _hdl                   | up53DzBISPq248wq7IRBGg | 5gOMz5JNTKud05cCiAsiRA |
+========================+========================+========================+
| KQdIrIUNQIyMAxJWpazNAw | NULL                   | null                   |
+------------------------+------------------------+------------------------+
1 tuple
````
You can see that `up53DzBISPq248wq7IRBGg` is the string `"NULL"` whereas `5gOMz5JNTKud05cCiAsiRA` is a literal `null`

If I make this same query like this:
````
db.query(`SELECT "_hdl", "up53DzBISPq248wq7IRBGg", "5gOMz5JNTKud05cCiAsiRA" FROM "eic39_tagged_item" WHERE "_hdl" = 'KQdIrIUNQIyMAxJWpazNAw'`, true)
.then(results => {
  console.log(
    results.data
  )
})
````
I get a response like this, with both columns set to literal `null`:
````
[ { _hdl: 'KQdIrIUNQIyMAxJWpazNAw',
    up53DzBISPq248wq7IRBGg: null,
    '5gOMz5JNTKud05cCiAsiRA': null } ]
````
I think this is related to this line: https://github.com/MonetDB/monetdb-nodejs/blob/2a2101dcf78bf511910475bceca34944c1539e2e/src/mapi-connection.js#L454

Any advice? Thanks!

**Comment by sjoerdmullender** [comment]
What I think is happening is that the fact that one of the NULL values reported was quoted and one wasn't (the actual string is quoted, the "unknown value" represented as NULL is not).  So the test you point to should also take into consideration whether quotes have been seen.

**Comment by MattCollins84** [comment]
Yea that was my assumption too, however I couldn't get my head around how
to start with that just yet!
