### ISSUE TITLE
promise request does not finish and return in case of query error

### ISSUE THREAD

**Issue by staircaseblog** [MonetDB/monetdb-nodejs#2]
Thanks for answering my last query superfast!! I have a problem which i am not sure where it comes from. Thanks in advance for this request.

What do i want to achieve: I want to run several simple correlation column to column (e1 against e2, ...) querys against monetdb and fire off a bunch of request using promise based API.

Using q.all(promises) i want to collect the return of all those promises. Now I tap into the following issues and i am stuck.

Software status:
├── monetdb@1.1.0
├── q@1.4.1

**Issue 1: **When Correlation function reports error in MonetDB it appears to never resolve. I dont get any output from the q.all(promises).then:

sql>SELECT corr(e1, e10) from uvrr WHERE identifikation = 'b7somekey' and rahmen = 3;
division by zero. The program does not return. Something prevents it from finishing. It looks q.all is never returning.

Question: From the samples of the page i cannot figure out error handling individually per promise and per q.all(promises).

**Issue 2:** When i run the code in all combinations which return no error on correlation function (e1 against e2 ... e9) i have an output, but the program does not return. q.all(promises).then is entered. However something prevents it from finishing.

....
{ type: 'table',
    queryid: 0,
    rows: 1,
    cols: 1,
    structure: [ [Object] ],
    col: { L1: 0 },
    data: [ [Object] ] },
  { type: 'table',
    queryid: 0,
    rows: 1,
    cols: 1,
    structure: [ [Object] ],
    col: { L1: 0 },
    data: [ [Object] ] },
  { type: 'table',
    queryid: 0,
    rows: 1,
    cols: 1,
    structure: [ [Object] ],
    col: { L1: 0 },
    data: [ [Object] ] } ]
[ [ 0.6402342680233604 ] ]
[ [ 0.42005952472000013 ] ]
[ [ 0.481698295545429 ] ]
[ [ 0.7019200091009924 ] ]
[ [ -0.3776878285894189 ] ]
[ [ -0.4578978628805585 ] ]
[ [ 0.6510690799242778 ] ]
[ [ -0.5732567440092465 ] ]

Any Idea? Thanks in advance

Here the troublemaker:

var options = {
    host     : 'localhost',
    port     : 50000,
    dbname   : 'wyh',
    user     : 'monetdb',
    password : 'monetdb'
};

var q = require('q');

var AUSWERTUNG = {
    _db: null,

    getDb: function () {
        if (!AUSWERTUNG._db) {
            console.log("connect to monetdb");
            var MDB = require('monetdb')();
            AUSWERTUNG._db = new MDB(options);
            AUSWERTUNG._db.connect();
            //TODO: Fehlerbehandlung
            console.log(AUSWERTUNG._db);
        }
        return AUSWERTUNG._db;
    },

    getCorrIndividual: function() {
        var db = AUSWERTUNG.getDb();

        if (db == null) {
            console.error('db is null');
        }

        //for those columns the correlation works with no error
        var keys = ["e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9"];

        //column e10 creates a division by zero in monetdb - NO OUTPUT AT ALL and no FINISH of program
        //var keys = ["e10"];

        var promises = keys.map(function (f) {
            //var sql = "SELECT corr(e1, e2) FROM uvrr where identifikation = 'b7somekey'";

            // THIS ONE LEADS TO OUTPUT BUT HANGS infinitely
            var sql = "SELECT corr(e1, ".concat(f, ") from uvrr WHERE identifikation = 'b7somekey' and rahmen = 3");
            return db.query(sql);

            // THIS ONE LEADS TO NO OUTPUT
            //var sql = 'SELECT CORR(?,?) FROM uvrr WHERE identifikation = ? AND rahmen = ?';
            //var para = ['e1', f, 'b7somekey', 3];
            //return db.query(sql, para);
        });

        return promises;
    },

    getCorr: function() {
        var promises = AUSWERTUNG.getCorrIndividual();
        console.log(promises);

        q.all(promises).then(function(responseArray) {
            console.log(responseArray);

            responseArray.forEach(function(c,i,a) {
               console.log(c.data);
            });
        });
    },

    getSummary: function() {
        //Stat queries for summary dashboard
    },

    run: function() {
        AUSWERTUNG.getDb();
        AUSWERTUNG.getCorr();
    }
};

module.exports = AUSWERTUNG;

AUSWERTUNG.run();

**Comment by staircaseblog** [comment]
I simplified the program and took out the q.all call. Actually the program does not return and what concerns me more is that i dont know how to handle error situations. Tha call i am doing is creating a div by zero error and the program does not come back with an error.

sql>SELECT corr(e1, e10) from uvrr WHERE identifikation = 'b7somekey' and rahmen = 3;
division by zero.
sql>


var options = {
    host     : 'localhost',
    port     : 50000,
    dbname   : 'wyh',
    user     : 'monetdb',
    password : 'monetdb'
};

var AUSWERTUNG = {
    _db: null,

    getDb: function () {
        if (!AUSWERTUNG._db) {
            console.log("connect to monetdb");
            var MDB = require('monetdb')();
            AUSWERTUNG._db = new MDB(options);
            AUSWERTUNG._db.connect();
            //TODO: Fehlerbehandlung
            console.log(AUSWERTUNG._db);
        }
        return AUSWERTUNG._db;
    },

    getCorrOne: function() {
        var db = AUSWERTUNG.getDb();

        if(db == null) {
            console.log("db not initialized properly");
        }

        var sql = "SELECT corr(e1, e10) from uvrr WHERE identifikation = 'b7somekey' and rahmen = 3";
        console.log(sql);

        db.query(sql).thenResolve(function(s) {
            console.log(s);
        }).thenReject(function(rej){
            console.log(rej);
        });

        db.query(sql).then(function(r){
            console.log(r);
        });

        db.query(sql).when(function(w) {
            console.log(w);
        });
    }
};

module.exports = AUSWERTUNG;

AUSWERTUNG.getCorrOne();

**Comment by staircaseblog** [comment]
var options = {
    host     : 'localhost',
    port     : 50000,
    dbname   : 'wyh',
    user     : 'monetdb',
    password : 'monetdb'
};

var MDB = require('monetdb')();
var m_db = new MDB(options);

var sql = "SELECT corr(e1, e2) from uvrr WHERE identifikation = 'b7somekey' and rahmen = 3";
console.log(sql);

m_db.query(sql).then(function(res) {
    console.log(res);
},function(err) {
    console.log(err);
});

**Comment by staircaseblog** [comment]
Ok, my q.all call now looks like this and when i have a promise inside which does not resolve the entire does not resolve. Here i get the error propagated.

q.all(promises).then(function(responseArray) {
            console.log(responseArray);

            responseArray.forEach(function(c,i,a) {
               console.log(c.data);
            });
        }, function(err) {
            console.log(err);
        });

**Comment by staircaseblog** [comment]
To finish my monologue here - its all an RTFM issue. Though the M is a bit hidden sometimes.

Two things which fixede the problem:

1.) use q.allSettled instead of q.all: q.allSettled does not break on unfulfilled promises. Then filter the fulfilled ones. e.g. like this:

q.allSettled(promises).then(function(responseArray) {
            console.log(responseArray);

            responseArray.forEach(function(c,i,a) {
                if(c.state && c.state == 'fulfilled') {

2.) call close() on the db handler fixes the termination issue

Best

**Comment by hannesmuehleisen** [comment]
@rcijvat perhaps doc can be updated?

**Comment by rcijvat** [comment]
Hello there,

Thanks for sharing your experiences. Are you now saying that you do not have problems anymore with queries that never resolve or get rejected? Because q.allSettled only resolves after all promises in it have either been resolved or rejected.

**Comment by staircaseblog** [comment]
Hi,

tx for your response. I was precise with my wording. I thought in the beginning it does not resolve, but i wasnt able to catch the rejection properly. 
I would have a problem with never resolved or rejected ones with the way i am doing it now. 

I am ok, tx
