### ISSUE TITLE
Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by Abashevav** [MonetDB/monetdb-nodejs#23]
We get the error "WARNING Socket error occurred: Error: read ETIMEDOUT".
This results in long responses from MonetDB due to the fact that the reconnect happens after a while.

**System description:**
We use the NextJS application and the created API to work with MonetDB.
We are using your NPM package ("monetdb" v1.3.3) along with the NPM package "monetdb-pool" v0.0.8. Both packages are the latest version.
NPM - v16.14
"poolOptions = { nrConnections: 8 }"

We carried out load testing and already at low load we started receive the error "WARNING Socket error occurred: Error: read ETIMEDOUT".
As a result, some requests that were sent to MonetDB returned a response after this error and subsequent reconnect. All requests were approximately the same and did not have any features.
```
WARNING Socket error occurred: Error: read ETIMEDOUT
WARNING Reconnect attempt 1/10 in 2 sec..
WARNING Reconnection succeeded.
```

**Description of the situation:**
* Started load testing
* In 25 minutes, the load gradually increased from 1 request per second to 4 requests per second
	! When we compared the project logs with the Nginx logs, we noticed that some requests did not have a response immediately after the request. But at the same time, the answer came after the received error and reconnect.
* In 25 minutes there were 22 such "stuck" requests. A total of ~2100 requests were launched
* The response times for these "stuck" requests ranged from 100 seconds to 950 seconds
* A total of 6 such errors were received. They were all within 2 minutes
* Load testing did not stop for another 1 hour and the load increased to 20 requests per second. But there were no more such mistakes!

What could be the reason for such an error? 
Have you encountered such a problem?
How is such an error handled in your library?
How can we make requests not "stuck"? Or, if such a problem occurred, the recconect occurred immediately?

**Comment by sstalin** [comment]
What MonetDB version are you using? Also, maybe it is worth to see if there are nay indication of why the timeout in the <your_db_farm>/merovingian.log

**Comment by Abashevav** [comment]
MonetDB 11.45.7-20220923
 
I'm afraid there are no more merovingian log file.
Every month we recreate MonetDB instances, the logs from old instances have already been deleted.
We will try to repeat this error on new instances, and then we can provide these logs?
 
Is it possible to do something without these logs now?

**Comment by sstalin** [comment]
Yes, if you can provide merovingian.log will perhaps shed more light on the situation. Meanwhile if you can assist us with a concrete test script that will help us reproduce the problem would be helpful. Also, there is a `reconnectTimeout` option that defaults to 2 sec, but I'm sure you are aware of it.

**Comment by sstalin** [comment]
I did a simple test with creating 100 connections with a sleep of `100ms` in between. I haven't encounter any problems at all. I did not use `monetdb-pool` library though just monetdb-nodejs driver. MonetDB was Sep2022 release.

**Comment by Abashevav** [comment]
A client who performs load testing in our application does not want to share complete information about the load that they use. No matter how much we asked him, he does not give us this information. All he tells us is:
`We ramped up 1 user every 5 secs up to 500users.`

According to our logs, we noticed that at the peak of the load, **25-30 requests per second** occur to MonetDB
Load testing duration ~ **1.5 hour**
The amount of data transfer in one request - **from 2000 to 20000 values**

I tried changing the "`reconnectTimeout`" option to 500 ms, but that caused connection problems, so I changed it back to default.
In the coming days, we will conduct our load tests to repeat this error, and also additionally check reconnectTimeout.
I will provide test results and `merovingian.log` file after that

Also, we will try to test without the monetdb-pool library, but this is a useful tool for us, especially given the large number of requests during load testing from the client

**Comment by sstalin** [comment]
I was able to reproduce the issue you are describing using the `monetdb-pool-nodejs` library with 64 concurrent client connections, e.g. `poolOptions = { nrConnections: 64}`. BTW 64 is the maximum concurrent clients MonetDB supports at the moment. I believe this relates to a race condition bug in the client connections in Monet which was recently fixed, namely this one  https://monetdb.org/hg/MonetDB/rev/5e976f70f957. So,  as I see it there is no fix to be added here at the moment. The patch will be available in the next MonetDB release.
