### ISSUE TITLE
it does not work properly when insert a bunch of records

### ISSUE THREAD

**Issue by hairinwind** [MonetDB/monetdb-nodejs#3]
Here is my code. 

var dbOptions = {
    dbname: "stock", 
    user: 'stock', 
	password: 'stock'
};

var MDB = require('monetdb')();

for (var i=0; i<50; i++) {
	console.log('insert ' + i);
	var conn = new MDB(dbOptions);
	conn.connect(); 
	conn.query("INSERT INTO symbol(symbol, market, description) values('1', '2', '3')");
	conn.close();
}

After I executed this, I only found 33 records in the database. I ran it a couple of times, I never got 50 records in the table. 

If I change 50 to 3000, I will get error on monetdb server console. 
!MALException:initClient:cannot fork new client thread

Thanks,

**Comment by hannesmuehleisen** [comment]
Indeed this looks like the connection is not properly closed.

**Comment by rcijvat** [comment]
Thanks for the heads up. I will look into this issue this week. For now it might be a good idea to not open this many connections, as every connection apparently executes in a separate thread in the MonetDB process.
And another question: when and how did you check the database contents after running the above code? Did you wait for all queries to finish before checking the contents of the database? And how did you check whether or not the queries were done?

**Comment by hairinwind** [comment]
About checking the result, I saw the nodejs already stopped, returned. Then I use the monetdb client to query the table and found 33 records were inserted. I waited a while, about 10 seconds and ran the query again, it still returned me 33 records.

**Comment by rcijvat** [comment]
The issue has been identified and fixed. It turned out to be a concurrency conflict, which can happen when multiple connections try to write to the same column of the same table. So in your case, 50 connections were trying to write to the same columns, which resulted in about half of them failing, causing the automatic commit mode to rollback these inserts. It was previously undetectable when a concurrency conflict occurred, but this has been fixed. The promise returned by your call to query now gets rejected with a concurrency conflict error message whenever this occurs.

Consider the following change to your code:

```
for (var i=0; i<50; i++) {
  console.log('insert ' + i);
  var conn = new MDB(dbOptions);
  conn.connect(); 
  conn.query("INSERT INTO symbol(symbol, market, description) values('1', '2', '3')").then(function() {
    console.log('successfully inserted a tuple');
  }, function(err) {
    console.log('could not insert your tuple: ' + err);
  });
  conn.close();
}
```

If you want to do a bulk insert, it would be advisable to use the COPY INTO statement for this, as it is highly optimized and will be much faster than individual insert statements.

**Comment by hairinwind** [comment]
I am sorry, was this fixed? 
I reinstalled the monetdb npm package. The version is now 1.1.2. 
Then I rerun the code. I still got the error. 

could not insert your tuple: Error: 40000!COMMIT: transaction is aborted because of concurrency conflicts, will ROLLBACK instead

Do I need to reinstall the monetdb server?

Thanks,

**Comment by rcijvat** [comment]
This is expected behavior. Like I said, this is caused by a concurrency conflict in MonetDB, as described in my previous comments. See my previous comments for suggestions on how to avoid this.

**Comment by rcijvat** [comment]
By the way, from your previous posts (here and on the monetdb-pool page) it seems like you misunderstood how you can use MonetDB connection objects. You do not have to open a new connection for every query you want to execute. You can leave it open and do as many queries you like on a single connection. This also ensures that you will get no concurrency conflicts. Adjusted example:

```javascript

var conn = new MDB(dbOptions);
conn.connect(); 
for (var i=0; i<50; i++) {
  console.log('insert ' + i);
  conn.query("INSERT INTO symbol(symbol, market, description) values('1', '2', '3')").then(function() {
    console.log('successfully inserted a tuple');
  }, function(err) {
    console.log('could not insert your tuple: ' + err);
  });
}
conn.close();
```


Regarding your questions about monetdb-pool: you can use it in exactly this way as well, only then the queries are divided over multiple connections under the hood.
