### ISSUE TITLE
Add feature to return stream instead of full result

### ISSUE THREAD

**Issue by redexp** [MonetDB/monetdb-nodejs#4]
Hello

I have a lot of data in one table and I want to reduce results from it, but working with array of thousands rows is not very optimized. How about to add option to `.query()` method like `returnStream: true` and this method will return stream which will help to work with portions of data.

I already tried to understand how this lib works and I have proposition (if you say that it good idea I can try to implement it and make pull request). Right now you collecting data response from server to `_readStr` and only after that you start parsing it. What if we will collect only headers data and when tuples will come we will parse headers, throw them to stream and start parsing tuples online and each portion throw to stream. So first data event in our stream will be headers (without `data` property) `{type: 'table', structure: [...], ...}` and all other data events will be array of rows `[[1, 'value'], [2, 'value']]`

**Comment by hannesmuehleisen** [comment]
we would be happy to review a PR!

**Comment by redexp** [comment]
ok, I will try to find some time for this
