### ISSUE TITLE
Can auto commit be set via connect option. 

### ISSUE THREAD

**Issue by peterprib** [MonetDB/monetdb-nodejs#8]
Suggest it would be nice to have options such as this to be available at as connection options rather than having to go through overhead of SQL statements

**Comment by peterprib** [comment]
How does one set the connect to  auto commit mode off as "set autocommit=..." claims autocommit isn't a variable?

**Comment by sstalin** [comment]
Hi, 
Version 1.2.0 has the auto commit option for when connection is created. Apologies for the delayed response.
